import React from 'react'
import NO from './Test';

function Test1() {
    const list = [
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
      {
        header: "Confidentiality",
        desc: "• During your employment with Nexucon Consultancy Services Pvt Ltd, you will have access to confidential and proprietary information. You agree not to release or disclose such information, either directly or indirectly, unless required by law or with the express written consent of management, provided by an authorized officer.\n• Please review the contents of this offer carefully. If the terms of employment outlined in this agreement are acceptable to you, kindly confirm your acceptance by proposing your start date and signing this document. If not accepted within three days of receipt, this offer may lapse at the discretion of Nexucon Consultancy Services Pvt Ltd. I would like to express my genuine enthusiasm for the possibility of you joining our organization. I hope you find the terms of this offer both reasonable and appealing. Feel free to reach out if you have any questions.",
      },
    ];

 
  return (
    <div>
      <NO list={list} />
    </div>
  )
}

export default Test1
